name: loomi_project
description: "Loomi Flutter Project"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  get_it: ^9.0.5
  provider: ^6.1.5+1
  flutter_native_splash: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_native_splash:
  color: "#0D478C"
  image: assets/splash.png
  fullscreen: true      
  android_12:
    color: "#0D478C"
    image: assets/splash.png 
    icon_background_color: "#FFFFFF"